### ISSUE TITLE
mysqloolib

### ISSUE THREAD

**Issue by TheDeadScythe** [StrandedHeart/GMod-Web-Administrator-Plugin#1]
Couldn't include file 'includes\modules\mysqloolib.lua' (File not found) (@addons/_freds_admin/lua/autorun/server/sv_fredsadmin.lua (line 1))

[ERROR] addons/_freds_admin/lua/autorun/server/sv_fredsadmin.lua:1: Module not found!
  1. require - [C]:-1
   2. unknown - addons/_freds_admin/lua/autorun/server/sv_fredsadmin.lua:1

**Comment by StrandedHeart** [comment]
Hey @TheDeadScythe 

This plugin is actually very old! I can't even remember making it. Given that it is 3 years old with no updates I can no longer support it. I am more than happy to make you a custom one if you add me on steam at.

http://steamcommunity.com/id/notaporcupine/
